//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessLogicLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry I&apos;m running in bot mode now if you want a price check please send a message in the following format &apos;pc cardname1; cardname2; cardname3; etc&apos; be sure that you use semi-colons instead of commas..
        /// </summary>
        public static string BotMode {
            get {
                return ResourceManager.GetString("BotMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the mouse at the top left of the area you want to examine and click.  Then place the mouse at the bottom right corner of the area you want to examine and click again..
        /// </summary>
        public static string ChecksumInstructions {
            get {
                return ResourceManager.GetString("ChecksumInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;.
        /// </summary>
        public static string DeckFileFirstLine {
            get {
                return ResourceManager.GetString("DeckFileFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Deck xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;.
        /// </summary>
        public static string DeckFileSecondLine {
            get {
                return ResourceManager.GetString("DeckFileSecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;NetDeckID&gt;0&lt;/NetDeckID&gt;.
        /// </summary>
        public static string DeckFileThirdLine {
            get {
                return ResourceManager.GetString("DeckFileThirdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;Cards CatID=&quot;{0}&quot; Quantity=&quot;{1}&quot; Sideboard=&quot;false&quot; Name=&quot;&quot; Row=&quot;0&quot; Col=&quot;0&quot; /&gt;.
        /// </summary>
        public static string DeckListCardItem {
            get {
                return ResourceManager.GetString("DeckListCardItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/Deck&gt;.
        /// </summary>
        public static string DeckListEndFile {
            get {
                return ResourceManager.GetString("DeckListEndFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \0WishList.dek.
        /// </summary>
        public static string DeckListFileName {
            get {
                return ResourceManager.GetString("DeckListFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;PreconstructedDeckID&gt;0&lt;/PreconstructedDeckID&gt;.
        /// </summary>
        public static string DeckListFourthLine {
            get {
                return ResourceManager.GetString("DeckListFourthLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have found {0} cards worth {1} tickets for this trade.  This is not enough for a full ticket so I will store this as credit towards your next trade.  After this trade you will have {2} tickets worth of credit..
        /// </summary>
        public static string LessThanATicketFound {
            get {
                return ResourceManager.GetString("LessThanATicketFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected more tickets worth of cards/tickets than I found in your collection.  You will have to open another trade to get more credit before taking additional tickets..
        /// </summary>
        public static string MaxTradeAmountExceeded {
            get {
                return ResourceManager.GetString("MaxTradeAmountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a ticket or more worth of credit {0} for this trade, please take an appropriate number of tickets..
        /// </summary>
        public static string MoreThanATicketFound {
            get {
                return ResourceManager.GetString("MoreThanATicketFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press CONFIRM..
        /// </summary>
        public static string PleasePressConfirm {
            get {
                return ResourceManager.GetString("PleasePressConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry but I only allow 70 price checks every 5 minutes and you have met your limit for the last 5 minutes, please do the request later..
        /// </summary>
        public static string PriceCheckLimit {
            get {
                return ResourceManager.GetString("PriceCheckLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [sV] {0} *{3}* |BuyPrice: {1}| |SellPrice: {2}|  .
        /// </summary>
        public static string PriceCheckResult {
            get {
                return ResourceManager.GetString("PriceCheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for shopping.  Be sure to add me to your buddy list and please come again!.
        /// </summary>
        public static string ThankYouMessage {
            get {
                return ResourceManager.GetString("ThankYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown card(s) requested for price check..
        /// </summary>
        public static string UnknownCard {
            get {
                return ResourceManager.GetString("UnknownCard", resourceCulture);
            }
        }
    }
}
